/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as AuthenticatedTreesRouteImport } from './routes/_authenticated/trees'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPestsRouteImport } from './routes/_authenticated/pests'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedIrrigationRouteImport } from './routes/_authenticated/irrigation'
import { Route as AuthenticatedFertilizationRouteImport } from './routes/_authenticated/fertilization'
import { Route as AuthenticatedFarmRouteImport } from './routes/_authenticated/farm'
import { Route as AuthenticatedDiseaseRouteImport } from './routes/_authenticated/disease'
import { Route as AuthenticatedCropsRouteImport } from './routes/_authenticated/crops'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as ApiPublicDailyBriefRouteImport } from './routes/api/public/daily-brief'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreesRoute = AuthenticatedTreesRouteImport.update({
  id: '/trees',
  path: '/trees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPestsRoute = AuthenticatedPestsRouteImport.update({
  id: '/pests',
  path: '/pests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIrrigationRoute = AuthenticatedIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFertilizationRoute =
  AuthenticatedFertilizationRouteImport.update({
    id: '/fertilization',
    path: '/fertilization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmRoute = AuthenticatedFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiseaseRoute = AuthenticatedDiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCropsRoute = AuthenticatedCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDailyBriefRoute = ApiPublicDailyBriefRouteImport.update({
  id: '/api/public/daily-brief',
  path: '/api/public/daily-brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/crops': typeof AuthenticatedCropsRoute
  '/disease': typeof AuthenticatedDiseaseRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/fertilization': typeof AuthenticatedFertilizationRoute
  '/irrigation': typeof AuthenticatedIrrigationRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pests': typeof AuthenticatedPestsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/trees': typeof AuthenticatedTreesRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/daily-brief': typeof ApiPublicDailyBriefRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/crops': typeof AuthenticatedCropsRoute
  '/disease': typeof AuthenticatedDiseaseRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/fertilization': typeof AuthenticatedFertilizationRoute
  '/irrigation': typeof AuthenticatedIrrigationRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pests': typeof AuthenticatedPestsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/trees': typeof AuthenticatedTreesRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/daily-brief': typeof ApiPublicDailyBriefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/crops': typeof AuthenticatedCropsRoute
  '/_authenticated/disease': typeof AuthenticatedDiseaseRoute
  '/_authenticated/farm': typeof AuthenticatedFarmRoute
  '/_authenticated/fertilization': typeof AuthenticatedFertilizationRoute
  '/_authenticated/irrigation': typeof AuthenticatedIrrigationRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pests': typeof AuthenticatedPestsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/trees': typeof AuthenticatedTreesRoute
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/daily-brief': typeof ApiPublicDailyBriefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai'
    | '/crops'
    | '/disease'
    | '/farm'
    | '/fertilization'
    | '/irrigation'
    | '/onboarding'
    | '/pests'
    | '/profile'
    | '/timeline'
    | '/trees'
    | '/weather'
    | '/api/stt'
    | '/api/tts'
    | '/api/public/daily-brief'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ai'
    | '/crops'
    | '/disease'
    | '/farm'
    | '/fertilization'
    | '/irrigation'
    | '/onboarding'
    | '/pests'
    | '/profile'
    | '/timeline'
    | '/trees'
    | '/weather'
    | '/api/stt'
    | '/api/tts'
    | '/'
    | '/api/public/daily-brief'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai'
    | '/_authenticated/crops'
    | '/_authenticated/disease'
    | '/_authenticated/farm'
    | '/_authenticated/fertilization'
    | '/_authenticated/irrigation'
    | '/_authenticated/onboarding'
    | '/_authenticated/pests'
    | '/_authenticated/profile'
    | '/_authenticated/timeline'
    | '/_authenticated/trees'
    | '/_authenticated/weather'
    | '/api/stt'
    | '/api/tts'
    | '/_authenticated/'
    | '/api/public/daily-brief'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicDailyBriefRoute: typeof ApiPublicDailyBriefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trees': {
      id: '/_authenticated/trees'
      path: '/trees'
      fullPath: '/trees'
      preLoaderRoute: typeof AuthenticatedTreesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pests': {
      id: '/_authenticated/pests'
      path: '/pests'
      fullPath: '/pests'
      preLoaderRoute: typeof AuthenticatedPestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irrigation': {
      id: '/_authenticated/irrigation'
      path: '/irrigation'
      fullPath: '/irrigation'
      preLoaderRoute: typeof AuthenticatedIrrigationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fertilization': {
      id: '/_authenticated/fertilization'
      path: '/fertilization'
      fullPath: '/fertilization'
      preLoaderRoute: typeof AuthenticatedFertilizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farm': {
      id: '/_authenticated/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof AuthenticatedFarmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disease': {
      id: '/_authenticated/disease'
      path: '/disease'
      fullPath: '/disease'
      preLoaderRoute: typeof AuthenticatedDiseaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crops': {
      id: '/_authenticated/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof AuthenticatedCropsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/daily-brief': {
      id: '/api/public/daily-brief'
      path: '/api/public/daily-brief'
      fullPath: '/api/public/daily-brief'
      preLoaderRoute: typeof ApiPublicDailyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedCropsRoute: typeof AuthenticatedCropsRoute
  AuthenticatedDiseaseRoute: typeof AuthenticatedDiseaseRoute
  AuthenticatedFarmRoute: typeof AuthenticatedFarmRoute
  AuthenticatedFertilizationRoute: typeof AuthenticatedFertilizationRoute
  AuthenticatedIrrigationRoute: typeof AuthenticatedIrrigationRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPestsRoute: typeof AuthenticatedPestsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedTreesRoute: typeof AuthenticatedTreesRoute
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedCropsRoute: AuthenticatedCropsRoute,
  AuthenticatedDiseaseRoute: AuthenticatedDiseaseRoute,
  AuthenticatedFarmRoute: AuthenticatedFarmRoute,
  AuthenticatedFertilizationRoute: AuthenticatedFertilizationRoute,
  AuthenticatedIrrigationRoute: AuthenticatedIrrigationRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPestsRoute: AuthenticatedPestsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedTreesRoute: AuthenticatedTreesRoute,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicDailyBriefRoute: ApiPublicDailyBriefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
